langauge: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t dwolfzero/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true dwolfzero/react-test yarn test

after_success:
    - docker build -t dwolfzero/multi-client ./client
    - docker build -t dwolfzero/multi-nginx ./nginx
    - docker build -t dwolfzero/multi-server ./server
    - docker build -t dwolfzero/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take images and push to docker hub
    - docker push dwolfzero/multi-client
    - docker push dwolfzero/multi-nginx
    - docker push dwolfzero/multi-server
    - docker push dwolfzero/multi-worker

deploy:
    provider: elasticbeanstalk
    region: ap-southeast-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-southeast-1-247985182982
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
